package en.swingy.equipement.weapon;

import java.util.Random;

public enum WeaponEnum {
	KINGS_SWORD_OF_HASTE("King's Sword of Haste"),
	GRISWOLDS_WORN_EDGE("Griswold's Worn Edge"),
	GRISWOLDS_EDGE("Griswold's Edge"),
	GHOUL_KINGS_BLADE("Ghoul King's Blade"),
	GOD_BUTCHER("God Butcher"),
	QUINQUENNIAL_SWORD("Quinquennial Sword"),
	AMBERWING("Amberwing"),
	SECOND_QUINQUENNIAL_SWORD("Second Quinquennial Sword"),
	SHORT_SWORD("Short Sword"),
	SABRE("Sabre"),
	BROADSWORD("Broadsword"),
	MONSTER_HUNTER("Monster Hunter"),
	WILDWOOD("Wildwood"),
	LONGSWORD("Longsword"),
	FALCHION("Falchion"),
	RAKANISHUS_BLADE("Rakanishu's Blade"),
	SCIMITAR("Scimitar"),
	BORNS_SEARING_SPITE("Born's Searing Spite"),
	WAR_SWORD("War Sword"),
	BASTARD_SWORD("Bastard Sword"),
	THE_ANCIENT_BONESABER_OF_ZUMAKALIS("The Ancient Bonesaber of Zumakalis"),
	DOOMBRINGER("Doombringer"),
	GLADIUS("Gladius"),
	SPECTRUM("Spectrum"),
	RIMEHEART("Rimeheart"),
	FULMINATOR("Fulminator"),
	EXARIAN("Exarian"),
	THUNDERFURY_BLESSED_BLADE_OF_THE_WINDSEEKER("Thunderfury, Blessed Blade of the Windseeker"),
	GIFT_OF_SILARIA("Gift of Silaria"),
	CUTLASS("Cutlass"),
	BATTLE_SWORD("Battle Sword"),
	KNIGHT_SWORD("Knight Sword"),
	DAO("Dao"),
	SHAMSHIR("Shamshir"),
	RAID_SWORD("Raid Sword"),
	ANCIENT_SWORD("Ancient Sword"),
	SEVER("Sever"),
	SKYCUTTER("Skycutter"),
	SPATHA("Spatha"),
	PIRATE_SWORD("Pirate Sword"),
	STRONG_SWORD("Strong Sword"),
	KING_BLADE("King Blade"),
	TULWAR("Tulwar"),
	SAIF("Saif"),
	CONQUEST_SWORD("Conquest Sword"),
	RUNE_SWORD("Rune Sword"),
	DEVIL_TONGUE("Devil Tongue"),
	AZUREWRATH("Azurewrath"),
	GRISWOLDS_MASTERPIECE("Griswold's Masterpiece"),
	CHAMPION_SWORD("Champion Sword"),
	TSUNAMI_BLADE("Tsunami Blade"),
	SWORD_OF_MEDIOCRITY("Sword of Mediocrity"),
	SWORD_OF_ILL_WILL("Sword of Ill Will"),
	GRISWOLDS_PERFECTION("Griswold's Perfection"),
	BORNS_FURIOUS_WRATH("Born's Furious Wrath"),
	DEATHWISH("Deathwish"),
	LITTLE_ROGUE("Little Rogue"),
	IN_GEOM("In-geom"),
	THE_SLANDERER("The Slanderer"),
	SHARD_OF_HATE("Shard of Hate"),
	THE_TWISTED_SWORD("The Twisted Sword"),
	STEFFONS_HEAVY_LANCE("Steffon's Heavy Lance"),
	JAVELIN("Javelin"),
	FUSCINA("Fuscina"),
	SPEAR("Spear"),
	SPEAR_OF_JAIRO("Spear of Jairo"),
	HASTA("Hasta"),
	PILUM("Pilum"),
	SCRIMSHAW("Scrimshaw"),
	ARREATS_LAW("Arreat's Law"),
	ANGON("Angon"),
	ASSEGAI("Assegai"),
	WAR_SPEAR("War Spear"),
	SPONTOON("Spontoon"),
	THE_THREE_HUNDREDTH_SPEAR("The Three Hundredth Spear"),
	YARI("Yari"),
	HARPOON("Harpoon"),
	IMPALER("Impaler"),
	EMPYREAN_MESSENGER("Empyrean Messenger"),
	VEL("Vel"),
	CENTURION_SPEAR("Centurion Spear"),
	QIANG("Qiang"),
	HONED_SPEAR("Honed Spear"),
	AKANESH_THE_HERALD_OF_RIGHTEOUSNESS("Akanesh, the Herald of Righteousness"),
	DISEMBOWELER("Disemboweler"),
	CLUB("Club"),
	MACE_OF_THE_CROWS("Mace of the Crows"),
	WIRTS_LEG("Wirt's Leg"),
	CUDGEL("Cudgel"),
	ODYN_SON("Odyn Son"),
	MORNING_STAR("Morning Star"),
	MACE("Mace"),
	MAD_MONARCHS_SCEPTER("Mad Monarch's Scepter"),
	FLANGED_MACE("Flanged Mace"),
	WIRTS_ORIGINAL_LEG("Wirt's Original Leg"),
	HAMMER("Hammer"),
	WAR_GAVEL("War Gavel"),
	TELRANDENS_HAND("Telranden's Hand"),
	NUTCRACKER("Nutcracker"),
	BLUDGEON("Bludgeon"),
	SOLANIUM("Solanium"),
	JACES_HAMMER_OF_VIGILANCE("Jace's Hammer of Vigilance"),
	SPIKED_BATON("Spiked Baton"),
	WAR_MACE("War Mace"),
	GADA("Gada"),
	PERNACH("Pernach"),
	HEAVY_HAMMER("Heavy Hammer"),
	NEANDERTHAL("Neanderthal"),
	WAR_HAMMER("War Hammer"),
	NAILBITER("Nailbiter"),
	SKULL_CRUSHER("Skull Crusher"),
	TRUNCHEON("Truncheon"),
	DEATH_MACE("Death Mace"),
	TRIPYOR("Tripyor"),
	SUN_KEEPER("Sun Keeper"),
	ECHOING_FURY("Echoing Fury"),
	DEMOLISHER("Demolisher"),
	CRAG_HAMMER("Crag Hammer"),
	EARTHSHATTER("Earthshatter"),
	GOEDENDAG("Goedendag"),
	BRUTALIZER("Brutalizer"),
	DEVASTATOR("Devastator"),
	SKULLSPLITTER("Skullsplitter"),
	SIMPLE_DAGGER("Simple Dagger"),
	SHIV("Shiv"),
	SHORT_DAGGER("Short Dagger"),
	DAGGER("Dagger"),
	THE_CLIPPER("The Clipper"),
	ENVIOUS_BLADE("Envious Blade"),
	POIGNARD("Poignard"),
	STILETTO("Stiletto"),
	SKIVER("Skiver"),
	PIG_STICKER("Pig Sticker"),
	THE_HORADRIC_HAMBURGER("The Horadric Hamburger"),
	JAGGED_DAGGER("Jagged Dagger"),
	KINDJAL("Kindjal"),
	PUGIO("Pugio"),
	RONDEL("Rondel"),
	SCRAMASAX("Scramasax"),
	MAIN_GAUCHE("Main Gauche"),
	SPINE("Spine"),
	KUKRI("Kukri"),
	PAVADE("Pavade"),
	CINQUEDEA("Cinquedea"),
	SKAIN("Skain"),
	PIERCER("Piercer"),
	DARKBLADE("Darkblade"),
	BLOOD_MAGIC_BLADE("Blood-Magic Blade"),
	WIZARDSPIKE("Wizardspike"),
	BASILARD("Basilard"),
	KINGSPORT_BLADE("Kingsport Blade"),
	KARLEIS_POINT("Karlei's Point"),
	PUNYAL("Punyal"),
	EUN_JANG_DO("Eun-jang-do"),
	LORD_GREENSTONES_FAN("Lord Greenstone's Fan"),
	BLOOD_MAGIC_EDGE("Blood-Magic Edge"),
	THE_BUTCHERS_CLEAVER("The Butcher's Cleaver"),
	HAND_AXE("Hand Axe"),
	AIDANS_REVENGE("Aidan's Revenge"),
	WEATHERED_HAND_AXE("Weathered Hand Axe"),
	BROAD_AXE("Broad Axe"),
	DOUBLE_AXE("Double Axe"),
	GENZANIKU("Genzaniku"),
	HEAVY_AXE("Heavy Axe"),
	BATTLE_AXE("Battle Axe"),
	MARAUDER_AXE("Marauder Axe"),
	SOLDIER_AXE("Soldier Axe"),
	FLESH_TEARER("Flesh Tearer"),
	HATCHET("Hatchet"),
	ONO("Ono"),
	HACK("Hack"),
	BULLOVA("Bullova"),
	THE_WEDGE("The Wedge"),
	ADZE("Adze"),
	CHOPPER("Chopper"),
	TOPOROK("Toporok"),
	THE_BUTCHERS_SICKLE("The Butcher's Sickle"),
	MASAKARI("Masakari"),
	TOMAHAWK("Tomahawk"),
	CRESCENT_AXE("Crescent Axe"),
	ARREAT_AXE("Arreat Axe"),
	BALESTARIUS("Balestarius"),
	SKY_SPLITTER("Sky Splitter"),
	THE_BURNING_AXE_OF_SANKIS("The Burning Axe of Sankis"),
	ARCH_AXE("Arch Axe"),
	SKARTARAN_AXE("Skartaran Axe"),
	GALRAKI("Galraki"),
	HALLOWED_STORM("Hallowed Storm"),
	EXECUTIONERS_AXE("Executioner's Axe"),
	HALLOWED_BREACH("Hallowed Breach"),
	UTARS_ROAR("Utar's Roar"),
	DIRE_AXE("Dire Axe"),
	MORDULLUS_PROMISE("Mordullu's Promise");

	private final String label;

	WeaponEnum(String label) {
		this.label = label;
	}

	public String getLabel() {
		return label;
	}

	public static String findAssetByName(String name) {
		WeaponEnum[] values = WeaponEnum.values();
		for (WeaponEnum value : values) {
			if (value.getLabel().equals(name)) {
				return WeaponAssets.getAsset(value.name());
			}
		}
		return null;
	}

	public static String getRandom() {
		WeaponEnum[] values = WeaponEnum.values();
		int index = new Random().nextInt(values.length);
		return values[index].getLabel();
	}
}