package en.swingy.equipement.weapon;

import java.util.Random;

public enum WeaponEnum {
	ADZE("Adze"),
	AIDANS_REVENGE("Aidan's Revenge"),
	AKANESH_THE_HERALD_OF_RIGHTEOUSNESS("Akanesh, the Herald of Righteousness"),
	AMBERWING("Amberwing"),
	ANCIENT_SWORD("Ancient Sword"),
	ANGON("Angon"),
	ARCH_AXE("Arch Axe"),
	ARREATS_LAW("Arreat's Law"),
	ARREAT_AXE("Arreat Axe"),
	ASSEGAI("Assegai"),
	BATTLE_AXE("Battle Axe"),
	BATTLE_SWORD("Battle Sword"),
	BASTARD_SWORD("Bastard Sword"),
	BALESTARIUS("Balestarius"),
	BASILARD("Basilard"),
	BLOOD_MAGIC_BLADE("Blood-Magic Blade"),
	BLOOD_MAGIC_EDGE("Blood-Magic Edge"),
	BORNS_FURIOUS_WRATH("Born's Furious Wrath"),
	BORNS_SEARING_SPITE("Born's Searing Spite"),
	BROADSWORD("Broadsword"),
	BROAD_AXE("Broad Axe"),
	BRUTALIZER("Brutalizer"),
	BULLOVA("Bullova"),
	CHAMPION_SWORD("Champion Sword"),
	CHOPPER("Chopper"),
	CINQUEDEA("Cinquedea"),
	CLUB("Club"),
	CRESCENT_AXE("Crescent Axe"),
	CONQUEST_SWORD("Conquest Sword"),
	CRAG_HAMMER("Crag Hammer"),
	CUDGEL("Cudgel"),
	DAGGER("Dagger"),
	DARKBLADE("Darkblade"),
	DEATH_MACE("Death Mace"),
	DEATHWISH("Deathwish"),
	DEMOLISHER("Demolisher"),
	DEVASTATOR("Devastator"),
	DEVIL_TONGUE("Devil Tongue"),
	DISEMBOWELER("Disemboweler"),
	DIRE_AXE("Dire Axe"),
	DOOMBRINGER("Doombringer"),
	DOUBLE_AXE("Double Axe"),
	ECHOING_FURY("Echoing Fury"),
	EMPYREAN_MESSENGER("Empyrean Messenger"),
	ENVIOUS_BLADE("Envious Blade"),
	EXARIAN("Exarian"),
	EXECUTIONERS_AXE("Executioner's Axe"),
	FALCHION("Falchion"),
	FLESH_TEARER("Flesh Tearer"),
	FLANGED_MACE("Flanged Mace"),
	FUSCINA("Fuscina"),
	GADA("Gada"),
	GALRAKI("Galraki"),
	GENZANIKU("Genzaniku"),
	GHOUL_KINGS_BLADE("Ghoul King's Blade"),
	GIFT_OF_SILARIA("Gift of Silaria"),
	GLADIUS("Gladius"),
	GOD_BUTCHER("God Butcher"),
	HACK("Hack"),
	HAND_AXE("Hand Axe"),
	HARPOON("Harpoon"),
	HATCHET("Hatchet"),
	HEAVY_AXE("Heavy Axe"),
	HEAVY_HAMMER("Heavy Hammer"),
	HONED_SPEAR("Honed Spear"),
	IMPALER("Impaler"),
	IN_GEOM("In-geom"),
	JACES_HAMMER_OF_VIGILANCE("Jace's Hammer of Vigilance"),
	JAVELIN("Javelin"),
	JAGGED_DAGGER("Jagged Dagger"),
	KARLEIS_POINT("Karlei's Point"),
	KINDJAL("Kindjal"),
	KING_BLADE("King Blade"),
	KINGS_SWORD_OF_HASTE("King's Sword of Haste"),
	KINGSPORT_BLADE("Kingsport Blade"),
	KNIGHT_SWORD("Knight Sword"),
	KUKRI("Kukri"),
	LORD_GREENSTONES_FAN("Lord Greenstone's Fan"),
	LONGSWORD("Longsword"),
	LITTLE_ROGUE("Little Rogue"),
	MAIN_GAUCHE("Main Gauche"),
	MAD_MONARCHS_SCEPTER("Mad Monarch's Scepter"),
	MACE("Mace"),
	MACE_OF_THE_CROWS("Mace of the Crows"),
	MARAUDER_AXE("Marauder Axe"),
	MASAKARI("Masakari"),
	MORNING_STAR("Morning Star"),
	MORDULLUS_PROMISE("Mordullus Promise"),
	NAILBITER("Nailbiter"),
	NEANDERTHAL("Neanderthal"),
	NUTCRACKER("Nutcracker"),
	ODYN_SON("Odyn Son"),
	ONO("Ono"),
	PERNACH("Pernach"),
	PAVADE("Pavade"),
	PIERCER("Piercer"),
	PIRATE_SWORD("Pirate Sword"),
	POIGNARD("Poignard"),
	PUGIO("Pugio"),
	PUNYAL("Punyal"),
	QIANG("Qiang"),
	RAKANISHUS_BLADE("Rakanishu's Blade"),
	RAID_SWORD("Raid Sword"),
	RIMEHEART("Rimeheart"),
	RONDEL("Rondel"),
	SCRAMASAX("Scramasax"),
	SCRIMSHAW("Scrimshaw"),
	SEVER("Sever"),
	SIMPLE_DAGGER("Simple Dagger"),
	SHORT_DAGGER("Short Dagger"),
	SHIV("Shiv"),
	SHAMSHIR("Shamshir"),
	SKAIN("Skain"),
	SKARTARAN_AXE("Skartaran Axe"),
	SKIVER("Skiver"),
	SKY_SPLITTER("Sky Splitter"),
	SKULL_CRUSHER("Skull Crusher"),
	SKULLSPLITTER("Skullsplitter"),
	SOLANIUM("Solanium"),
	SPATHA("Spatha"),
	SPIKED_BATON("Spiked Baton"),
	SPINE("Spine"),
	SPEAR("Spear"),
	SPEAR_OF_JAIRO("Spear of Jairo"),
	SPONTOON("Spontoon"),
	STEFFONS_HEAVY_LANCE("Steffon's Heavy Lance"),
	STRONG_SWORD("Strong Sword"),
	SWORD_OF_ILL_WILL("Sword of Ill Will"),
	SWORD_OF_MEDIOCRITY("Sword of Mediocrity"),
	THE_ANCIENT_BONESABER_OF_ZUMAKALIS("The Ancient Bonesaber of Zumakalis"),
	THE_BURNING_AXE_OF_SANKIS("The Burning Axe of Sankis"),
	THE_BUTCHERS_CLEAVER("The Butcher's Cleaver"),
	THE_BUTCHERS_SICKLE("The Butcher's Sickle"),
	THE_CLIPPER("The Clipper"),
	THE_HORADRIC_HAMBURGER("The Horadric Hamburger"),
	THE_SLANDERER("The Slanderer"),
	THE_TWISTED_SWORD("The Twisted Sword"),
	TELRANDENS_HAND("Telranden's Hand"),
	THUNDERFURY_BLESSED_BLADE_OF_THE_WINDSEEKER("Thunderfury, Blessed Blade of the Windseeker"),
	TOMAHAWK("Tomahawk"),
	TRIPYOR("Tripyor"),
	TRUNCHEON("Truncheon"),
	TSUNAMI_BLADE("Tsunami Blade"),
	TULWAR("Tulwar"),
	UTARS_ROAR("Utar's Roar"),
	VEL("Vel"),
	WAR_GAVEL("War Gavel"),
	WAR_HAMMER("War Hammer"),
	WAR_MACE("War Mace"),
	WAR_SPEAR("War Spear"),
	WAR_SWORD("War Sword"),
	WEATHERED_HAND_AXE("Weathered Hand Axe"),
	WIRTS_LEG("Wirt's Leg"),
	WIRTS_ORIGINAL_LEG("Wirt's Original Leg"),
	WILDWOOD("Wildwood"),
	WIZARDSPIKE("Wizardspike");

	private final String label;

	WeaponEnum(String label) {
		this.label = label;
	}

	public String getLabel() {
		return label;
	}

	public static String getRandom() {
		WeaponEnum[] values = WeaponEnum.values();
		int index = new Random().nextInt(values.length);
		return values[index].getLabel();
	}
}
