package en.swingy.equipement.armor;

public enum ArmorAssets {
	AQUILA_CUIRASS("AQUILA_CUIRASS.png"),
	ARACHYRS_CARAPACE("ARACHYRS_CARAPACE.png"),
	ARCHON_ARMOR("ARCHON_ARMOR.png"),
	ARKAINES_VALOR("ARKAINES_VALOR.png"),
	ARMOR_OF_THE_KIND_REGENT("ARMOR_OF_THE_KIND_REGENT.png"),
	ASCENDED_ARMOR("ASCENDED_ARMOR.png"),
	ASTRAL_MAIL("ASTRAL_MAIL.png"),
	AUGHILDS_DOMINION("AUGHILDS_DOMINION.png"),
	AUGHILDS_RULE("AUGHILDS_RULE.png"),
	BALOR_ARMOR("BALOR_ARMOR.png"),
	BANDED_CUIRASS("BANDED_CUIRASS.png"),
	BATTLE_ARMOR("BATTLE_ARMOR.png"),
	BLACKTHORNES_SURCOAT("BLACKTHORNES_SURCOAT.png"),
	BLOODSONG_MAIL("BLOODSONG_MAIL.png"),
	BONEWEAVE_HAUBERK("BONEWEAVE_HAUBERK.png"),
	BORNS_FROZEN_SOUL("BORNS_FROZEN_SOUL.png"),
	BORNS_HEART_OF_STEEL("BORNS_HEART_OF_STEEL.png"),
	BREASTPLATE_OF_AKKHAN("BREASTPLATE_OF_AKKHAN.png"),
	BRIGANDINE_COAT("BRIGANDINE_COAT.png"),
	BRIGANDINE_OF_VALOR("BRIGANDINE_OF_VALOR.png"),
	CHAINGMAIL("CHAINGMAIL.png"),
	CHAIN_MAIL("CHAIN_MAIL.png"),
	CINDERCOAT("CINDERCOAT.png"),
	CLOTH_TUNIC("CLOTH_TUNIC.png"),
	CUIRASS_OF_THE_WASTES("CUIRASS_OF_THE_WASTES.png"),
	DEMONS_HEART("DEMONS_HEART.png"),
	DEMONS_MARROW("DEMONS_MARROW.png"),
	DOOM_ARMOR("DOOM_ARMOR.png"),
	ETCHED_JACKET("ETCHED_JACKET.png"),
	FIREBIRDS_BREAST("FIREBIRDS_BREAST.png"),
	GODLY_PLATE_OF_THE_WHALE("GODLY_PLATE_OF_THE_WHALE.png"),
	GOLDSKIN("GOLDSKIN.png"),
	HARNESS_OF_TRUTH("HARNESS_OF_TRUTH.png"),
	HEART_OF_IRON("HEART_OF_IRON.png"),
	HEART_OF_THE_CRASHING_WAVE("HEART_OF_THE_CRASHING_WAVE.png"),
	HEART_OF_THE_LIGHT("HEART_OF_THE_LIGHT.png"),
	HELLTOOTH_TUNIC("HELLTOOTH_TUNIC.png"),
	HIDE_TUNIC("HIDE_TUNIC.png"),
	IMMORTAL_KINGS_ETERNAL_REIGN("IMMORTAL_KINGS_ETERNAL_REIGN.png"),
	INARIUSS_CONVICTION("INARIUSS_CONVICTION.png"),
	INNAS_VAST_EXPANSE("INNAS_VAST_EXPANSE.png"),
	JADE_HARVESTERS_PEACE("JADE_HARVESTERS_PEACE.png"),
	JAZERAINT_MAIL("JAZERAINT_MAIL.png"),
	LAMELLARS_OF_JUSTICE("LAMELLARS_OF_JUSTICE.png"),
	LEATHER_DOUBLET("LEATHER_DOUBLET.png"),
	MANTLE_OF_THE_RYDRAELM("MANTLE_OF_THE_RYDRAELM.png"),
	MARAUDERS_CARAPACE("MARAUDERS_CARAPACE.png"),
	MARKINGS_OF_SAVAGES("MARKINGS_OF_SAVAGES.png"),
	MUNDUNUGUS_ROBE("MUNDUNUGUS_ROBE.png"),
	MYSTERY_CHEST_ARMOR("MYSTERY_CHEST_ARMOR.png"),
	PESTILENCE_ROBE("PESTILENCE_ROBE.png"),
	PLATE_MAIL("PLATE_MAIL.png"),
	RAEKORS_HEART("RAEKORS_HEART.png"),
	RAKKISGARD_ARMOR("RAKKISGARD_ARMOR.png"),
	RATHMAS_RIBCAGE_PLATE("RATHMAS_RIBCAGE_PLATE.png"),
	REQUIEM_CEREPLATE("REQUIEM_CEREPLATE.png"),
	ROBES_OF_THE_RYDRAELM("ROBES_OF_THE_RYDRAELM.png"),
	ROLANDS_BEARING("ROLANDS_BEARING.png"),
	SHI_MIZUS_HAORI("SHI_MIZUS_HAORI.png"),
	SOPHISTICATED_VEST("SOPHISTICATED_VEST.png"),
	SOVEREIGN_MAIL("SOVEREIGN_MAIL.png"),
	SPIRIT_OF_THE_EARTH("SPIRIT_OF_THE_EARTH.png"),
	SPLINT_CUIRASS("SPLINT_CUIRASS.png"),
	STYGIAN_HARNESS("STYGIAN_HARNESS.png"),
	SUNWUKOS_SOUL("SUNWUKOS_SOUL.png"),
	TAL_RASHAS_RELENTLESS_PURSUIT("TAL_RASHAS_RELENTLESS_PURSUIT.png"),
	THE_SHADOWS_BANE("THE_SHADOWS_BANE.png"),
	TRAGOULS_SCALES("TRAGOULS_SCALES.png"),
	TYPHONS_THORAX("TYPHONS_THORAX.png"),
	TYRAELS_MIGHT("TYRAELS_MIGHT.png"),
	ULIANAS_HEART("ULIANAS_HEART.png"),
	VYRS_ASTONISHING_AURA("VYRS_ASTONISHING_AURA.png"),
	WARLORD_PLATE("WARLORD_PLATE.png"),
	ZUNIMASSAS_MARROW("ZUNIMASSAS_MARROW.png");

	private static final String BASE_PATH = "ressources/assets/stuff/armor/";
	private final String path;

	ArmorAssets(String fileName) {
		this.path = BASE_PATH + fileName;
	}

	public String getPath() {
		return path;
	}

	@Override
	public String toString() {
		return path;
	}
}
