CREATE TABLE Hero (
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name" TEXT NOT NULL,
	"lv" INTEGER NOT NULL,
	"xp" INTEGER NOT NULL,
	"attack" INTEGER NOT NULL,
	"defense" INTEGER NOT NULL,
	"hit_points" INTEGER NOT NULL,
	"w_name" TEXT NOT NULL,
	"w_attack" INTEGER NOT NULL,
	"a_name" TEXT NOT NULL,
	"a_defense" INTEGER NOT NULL,
	"h_name" TEXT NOT NULL,
	"h_hp" INTEGER NOT NULL
);